### ISSUE TITLE
Latest release

### ISSUE THREAD

**Issue by W0rma** [Codeception/lib-asserts#2]
The latest release which adds compatibility with phpunit 9 was tagged as `1.2.0`. However, the tag before was `1.10.1`. Composer always tries to install the latest version - which is still `1.10.1`.

Maybe we can add a tag that is higher that `1.10.1`?

**Comment by kornrunner** [comment]
@Naktibalda ping

**Comment by Naktibalda** [comment]
I released 1.11.0

Versioning of this library is a bit messy,
When Symfony 5 came out my initial reaction was that it will be necessary to bump major version of Codeception to support it, so I tried to drop support of older versions of PHPUnit at the same time and remove dependencies on phpunit-wrapper.
It was necessary to release a version of this library before upgrading other components.
